Cellid numbers copied from [H01 default neuroglancer workspace](http://h01-dot-neuroglancer-demo.appspot.com/#!gs://h01-release/assets/neuroglancer_states/20210729/library_state.json)

In [1]:
import pandas as pd
import numpy as np

In [2]:
ss_list = [635743109, 2120664699, 2950980117, 3106947392, 3296832824, 3512752660, 3513951463, 3588284587, 3631312996, 3645170418, 3773716567, 3788376389, 3788551051, 3790844645, 3833230503, 3907682045, 3937466277, 3949920978, 3994337380, 4006748353, 4068088366, 4079680017, 4094078022, 4094501608, 4124300709, 4127236696, 4140858954, 4152247000, 4152861452, 4153108523, 4154686065, 4185377684, 4254761989, 4255432378, 4312742466, 4326699742, 4326818082, 4327955860, 4370590371, 4372430258, 4372868243, 4474214654, 4475484255, 4475995296, 4489268853, 4500948443, 4501838736, 4503782000, 4504145716, 4516965446, 4519199538, 4519243274, 4530384028, 4573881259, 4575925341, 4591898165, 4617509729, 4619654531, 4619873240, 4723890949, 4735542348, 4766773877, 4780076410, 4809949027, 4823076755, 4839473227, 4852629019, 4896065848, 4897964007, 4924801658, 4926903194, 4938804262, 4955754739, 4970736617, 4997163340, 5027124405, 5028934840, 5042588326, 5055801374, 5103080167, 5114905708, 5115534039, 5115869424, 5144808371, 5159205830, 5174375994, 5231832117, 5247730833, 5248446458, 5291856456, 5317129594, 5348623756, 5364977088, 5376877616, 5377446229, 5377927964, 5406487849, 5480120932, 5492969654, 5565128350, 5595249249, 5623693160, 5624832585, 5682402703, 5845146472, 5855979281, 5887240031, 5900396223, 5902484088, 5942899024, 5975984947, 5989857178, 6091581258, 6163710175, 6177990420, 6209498692, 6220712283, 6222230785, 6263276083, 6278138984, 6309603153, 6322687028, 6384842151, 6411635598, 6412233719, 6427024613, 6484377108, 6559179000, 6613785802, 6614928166, 6631059913, 6643164727, 6658406895, 6702705861, 6745384646, 6777258586, 6804898281, 6863842503, 7037463002, 7067117794, 12857642016, 13046505828, 13951650786, 14794814799, 15539757452, 21348269172, 21635455184, 22948012913, 27216368299, 28104985461, 28862498148, 29210178754, 29672577804, 29730222317, 29919408414, 29977680734, 30180955426, 30211441416, 30224642109, 30501462297, 30501870437, 30516077733, 30573824944, 30588382028, 30605127877, 30865392105, 30941549387, 31068084020, 31082523968, 31083559920, 31140649483, 31274759074, 31349195650, 31576899712, 31591499830, 32385180272, 33049905842, 33269227364, 33544164420, 33663789818, 33779853124, 33779985123, 37626413608, 38611762212, 38660748322, 38689468673, 39540618731, 41933255298, 42002712851, 42108919642]

In [3]:
len(ss_list)

190

In [4]:
L1 = []
L2 = [635743109, 2120664699, 2950980117, 27216368299, 28104985461, 28862498148, 37626413608, 38660748322, 38689468673]
L3 = [29210178754, 32385180272]
L4 = [3106947392, 3296832824, 3513951463, 3588284587, 3631312996, 3790844645, 3937466277, 4068088366, 4127236696, 4140858954, 4185377684, 4519243274, 5103080167, 5291856456, 5364977088, 21348269172, 29672577804, 29730222317, 30941549387, 31349195650, 38611762212, 42108919642]
L5 = [3512752660, 3645170418, 3773716567, 3788551051, 3833230503, 3907682045, 3949920978, 3994337380, 4094078022, 4094501608, 4124300709, 4152247000, 4152861452, 4153108523, 4154686065, 4254761989, 4255432378, 4312742466, 4326699742, 4326818082, 4327955860, 4372430258, 4372868243, 4474214654, 4475484255, 4475995296, 4489268853, 4501838736, 4503782000, 4504145716, 4516965446, 4519199538, 4575925341, 4591898165, 4619654531, 4619873240, 4723890949, 4766773877, 4780076410, 4809949027, 4823076755, 4839473227, 4852629019, 4896065848, 4897964007, 4924801658, 4926903194, 4938804262, 4955754739, 5027124405, 5028934840, 5042588326, 5055801374, 5114905708, 5115534039, 5115869424, 5144808371, 5159205830, 5174375994, 5231832117, 5247730833, 5248446458, 5348623756, 5376877616, 5377446229, 5377927964, 5406487849, 5595249249, 5624832585, 5682402703, 5845146472, 5887240031, 5902484088, 5975984947, 5989857178, 6091581258, 6163710175, 6209498692, 6222230785, 6309603153, 6384842151, 6411635598, 6412233719, 6427024613, 6484377108, 6559179000, 6631059913, 6702705861, 6777258586, 6804898281, 6863842503, 7037463002, 7067117794, 12857642016, 13046505828, 13951650786, 21635455184, 22948012913, 29977680734, 30180955426, 30211441416, 30224642109, 30501462297, 30501870437, 30516077733, 30573824944, 30588382028, 30605127877, 30865392105, 31083559920, 31274759074, 33663789818, 33779853124, 33779985123, 41933255298]
L6 = [3788376389, 4006748353, 4079680017, 4370590371, 4500948443, 4530384028, 4573881259, 4617509729, 4735542348, 4970736617, 4997163340, 5317129594, 5480120932, 5492969654, 5565128350, 5623693160, 5855979281, 5900396223, 6177990420, 6220712283, 6322687028, 6613785802, 6614928166, 6643164727, 6658406895, 6745384646, 14794814799, 15539757452, 31068084020, 31082523968, 31140649483, 31576899712, 31591499830, 33049905842, 33269227364, 39540618731]
WM = [5942899024, 6263276083, 6278138984, 33544164420, 42002712851]
unclassified = [29919408414]

checksum  
L1 0  
L2 9  
L3 2  
L4 22  
L5 115  
L6 36  
WM 5  
unclassified 1

In [5]:
# Creating a dictionary to hold the lists
lists_dict = {
    'L1': L1,
    'L2': L2,
    'L3': L3,
    'L4': L4,
    'L5': L5,
    'L6': L6,
    'WM': WM,
    'unclassified': unclassified
}

# Initialize an empty dataframe
df = pd.DataFrame(columns=['cellid', 'layer', 'cell_type', 'cell_subtype'])

# Iterate over the dictionary and concatenate each list as a dataframe
for layer, list_items in lists_dict.items():
    temp_df = pd.DataFrame({'cellid': list_items})
    temp_df['layer'] = layer
    temp_df['cell_type'] = 'neuron'
    temp_df['cell_subtype'] = 'spiny-stellate'
    df = pd.concat([df, temp_df], ignore_index=True)

# Display the resulting dataframe
df

          cellid         layer cell_type    cell_subtype
0      635743109            L2    neuron  spiny-stellate
1     2120664699            L2    neuron  spiny-stellate
2     2950980117            L2    neuron  spiny-stellate
3    27216368299            L2    neuron  spiny-stellate
4    28104985461            L2    neuron  spiny-stellate
..           ...           ...       ...             ...
185   6263276083            WM    neuron  spiny-stellate
186   6278138984            WM    neuron  spiny-stellate
187  33544164420            WM    neuron  spiny-stellate
188  42002712851            WM    neuron  spiny-stellate
189  29919408414  unclassified    neuron  spiny-stellate

[190 rows x 4 columns]

In [6]:
df.layer.value_counts()

L5              115
L6               36
L4               22
L2                9
WM                5
L3                2
unclassified      1
Name: layer, dtype: int64

In [7]:
# df.to_csv('h01_spiny_stellate_neurons_by_layer.csv', index=False)